GET http://localhost:3001/games

###

POST http://localhost:3001/game/new
Content-Type: application/json

{
  "gameName": "TestGame1",
  "entries": ["entry1", "entry2", "entry3"],
  "image": "/example.png"
}

###

PUT http://localhost:3001/game/element/652b254f005370bc6ff16bb6
Content-type: application/json

{
  "entries": "Betty, Mom, Dad, Lylea"
}

###

DELETE http://localhost:3001/game/delete/65299a75189474b2c361e46e
